version: 1.0.{build}

image: Visual Studio 2022

init:
- ps: |
    Write-Host "Downloading RDP helper..."
    Invoke-WebRequest https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1 -OutFile enable-rdp.ps1
    Write-Host "Enabling RDP..."
    ./enable-rdp.ps1

build_script:
- echo RDP is enabled. You can connect now.
- timeout 3600

test: off
